#!/usr/bin/perl

use strict;

my $ccf = shift or die;
my $ssf = shift or die;

open (my $cch, "<", $ccf) or die("no file: $ccf: $!");
open (my $ssh, "<", $ssf) or die("no file: $ssf: $!");

my %hash = ();

parse_tsv($cch, "coverage");
parse_tsv($ssh, "secondary_structure");

sub parse_tsv
{
   my $fh = shift @_ or die;
   my $id = shift @_ or die;
   while (<$fh>)
   {
      chomp;
      my ($x, $y) = split;
      $hash{$x}{$id} = $y;
   }
}

# header
print "x\tcoverage\tsecondary_structure\n";

# data rows
foreach my $x (sort {$a <=> $b} keys %hash)
{
   print "$x\t$hash{$x}{coverage}\t";
   print "$hash{$x}{secondary_structure}\n";
}


