#!/usr/bin/perl

use strict;

foreach my $arg (@ARGV)
{
   chomp;
   # warn "$_\n";
   #  read1_10-48_tfpuah.fastq.10-48_S.paired.sam.10-48_S_cladeE_v1.cc
   if ($arg =~ /read1_(\S+)_tfpuah/)
   {
      # print "[ \"$1\",";
   }
   if ($arg =~ /sam\.(\S+)\.cc/)
   {
      # print " \"$1\"],";
      print "$1";
   }
   print "\n";

}
